# zap logger configuration
zap:
  level: info
  format: console
  prefix: "[pegasuite]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
# system configuration
system:
  env: public # Change to "develop" to skip authentication for development mode
  addr: 8888
  router-prefix: ""
pgsql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
